[discord]
webhook_url = "https://discord.com/api/webhooks/1352737957068537978/8SRfxyPhIBXkquVMPHlM0gaPc77_I0mtCT4ZZqNVGB4TXiq4jt_nNgULX9at0a4o5Eim"
moder_webhook_url = "https://discord.com/api/webhooks/1353128558792540282/R3XGNC9N-a99M9wiV8gbP0qFqxJ1KseVOJYhpZLbE8ICjD8Z6TIDO4yLb-jJLRjBEI7f"
report_webhook_url = "https://discord.com/api/webhooks/1353170061275299964/KnvBBpm5SdJr087B_O2cxvY40bqqlZqYs2epllH1_9HPsf34GL28bgOZ8nMmaIGL07Ea"
discord_link = "https://discord.gg/CRgfn8e7KF"

[database]
path = "plugins/WAIServerCore/database"

[autorestart]
times = ["03:00", "12:00"]
timezone = "Europe/Moscow"

[motd]
enabled = true
messages = [
    "This feature is deprecated.",
    "Files are corrupted.",
    "Operation failed due to missing dependencies.",
    "Unexpected error occurred.",
    "Invalid input provided.",
    "Resource not found.",
    "Access denied.",
    "Out of memory.",
    "Null pointer exception.",
    "Invalid configuration detected.",
    "Connection timed out.",
    "Server is not responding.",
    "Insufficient permissions.",
    "Database is unreachable.",
    "Configuration file is missing.",
    "Module is not initialized.",
    "Invalid parameter value.",
    "Index out of bounds.",
    "File not found.",
    "Service unavailable.",
    "Operation aborted.",
    "The system is in an unstable state.",
    "Unexpected token encountered.",
    "Memory leak detected.",
    "Cache is full.",
    "Operation is not supported.",
    "Error while parsing data.",
    "Failed to load resource.",
    "Security breach detected.",
    "Dependency conflict found.",
    "Deprecated API used.",
    "Protocol mismatch error.",
    "Invalid session token.",
    "Unable to complete the request.",
    "Malformed request syntax.",
    "Disk quota exceeded.",
    "Service temporarily disabled.",
    "Operation canceled by user.",
    "Data type mismatch.",
    "Checksum validation failed.",
    "Network error occurred.",
    "Resource locked by another process.",
    "File system is read-only.",
    "Incompatible version detected.",
    "Unexpected shutdown.",
    "Failed to allocate resources.",
    "Environment variable is not set.",
    "Unsupported operation.",
    "Operation completed with warnings.",
    "System maintenance in progress."
]

[vape]
particle = "CAMPFIRE_COSY_SMOKE"
duration = 60

[virus]
max_radius = 15
base_interval = 20
infection_chance = 30.0
speed_increase = 0.1
consumable_items = [
    "APPLE",
    "BREAD",
    "ROTTEN_FLESH",
    "SPIDER_EYE"
]

[worldcontrol]
end_closed = true
nether_closed = true

[moderation]
allowed_players = ["AcryTrix"]
code_update_interval = 3600

[entity_tracker]
enabled = true
log_interval = 300

[fishing]
items = [
    { material = "COD", chance = 0.30 },
    { material = "SALMON", chance = 0.20 },
    { material = "PUFFERFISH", chance = 0.08 },
    { material = "TROPICAL_FISH", chance = 0.02 },
    { material = "BOWL", chance = 0.05 },
    { material = "LEATHER", chance = 0.05 },
    { material = "ROTTEN_FLESH", chance = 0.05 },
    { material = "STICK", chance = 0.05 },
    { material = "STRING", chance = 0.05 },
    { material = "BONE", chance = 0.03 },
    { material = "INK_SAC", chance = 0.01 },
    { material = "LILY_PAD", chance = 0.01 },
    { material = "TRIPWIRE_HOOK", chance = 0.005 },
    { material = "LEATHER_BOOTS", chance = 0.005 },
    { material = "BOOK", chance = 0.02 },
    { material = "FISHING_ROD", chance = 0.02 },
    { material = "ENCHANTED_BOOK", chance = 0.015 },
    { material = "BOW", chance = 0.01 },
    { material = "NAME_TAG", chance = 0.01 },
    { material = "SADDLE", chance = 0.01 },
    { material = "NAUTILUS_SHELL", chance = 0.005 },
    { material = "IRON_SWORD", chance = 0.005 },
    { material = "MENDING_BOOK", chance = 0.03 }
]

[settings_menu]
title = "§6Настройки"
discord_link = "https://discord.gg/example"
fill_empty_slots = true

[titles_menu]
title = "§6Управление титулами"
size = 36
item_name = "§a{title}"
available_title_item = "GREEN_TERRACOTTA"
unavailable_title_item = "BARRIER"
permissions = { warrior = "titles.title.warrior", mage = "titles.title.mage", brimstone = "titles.title.brimstone" }

[profile]
view_permission = "waiservercore.profile.view"