# Настройки вебхука
webhook-url: "https://discord.com/api/webhooks/1352737957068537978/8SRfxyPhIBXkquVMPHlM0gaPc77_I0mtCT4ZZqNVGB4TXiq4jt_nNgULX9at0a4o5Eim"
discord-link: "https://discord.gg/ваша_ссылка"

# Другие настройки плагина (если есть)