name: WAIServerCore
version: ${version}
main: org.wai.WAIServerCore
api-version: 1.21
author: AcryTrix, Xiwizloves
description: Core plugin for WAI server functionality

commands:
  alts:
    description: Показать альты игроков
    usage: /<command> [игрок]
  settings:
    description: Открыть меню настроек
    usage: /<command>
  link:
    description: Привязать Discord аккаунт
    usage: /<command> <код>
  linkadmin:
    description: Привязать аккаунт вручную (админ)
    usage: /<command> <игрок> <discord_id>
  mon:
    description: Активировать режим модератора
    usage: /<command> <код>
  moff:
    description: Деактивировать режим модератора
    usage: /<command>
  lc:
    description: Показать информацию об игроке
    usage: /<command> <ник>
  worldcontrol:
    description: Управление доступом к мирам
    usage: /<command> <open|close> <end|nether>
  titles:
    description: Управление титулами
    usage: /<command> [list|set|remove] [название]
  tradetitles:
    description: Обмен титулами с игроком
    usage: /<command> [игрок|accept|decline]
  report:
    description: Отправить репорт на игрока
    usage: /<command> <ник> <причина>

permissions:
  waiservercore.alts:
    description: Доступ к команде /alts
    default: op
  link.admin:
    description: Доступ к команде /linkadmin
    default: op
  wai.worldcontrol:
    description: Доступ к команде /worldcontrol
    default: op
  titles.title.*:
    description: Доступ ко всем титулам
    default: op
  permissions:
    waiservercore.reports.view:
      description: Доступ к просмотру репортов
      default: op